-- Create products table
create table public.products (
  id text primary key,
  name text not null,
  price numeric not null,
  category text not null default 'Geral',
  is_highlight boolean default false,
  image_url text,
  description text,
  details jsonb, -- Store dimensions and productionTime here
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.products enable row level security;

-- Create policy to allow public read access
create policy "Allow public read access" on public.products
  for select using (true);

-- Create policy to allow authenticated users to insert/update/delete
create policy "Allow authenticated insert" on public.products
  for insert with check (auth.role() = 'authenticated');

create policy "Allow authenticated update" on public.products
  for update using (auth.role() = 'authenticated');

create policy "Allow authenticated delete" on public.products
  for delete using (auth.role() = 'authenticated');

-- Create carousel_slides table
create table public.carousel_slides (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text,
  image text not null,
  link text, -- Using 'link' for cta (call to action link)
  button_text text, -- Using 'button_text' for cta label
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.carousel_slides enable row level security;

-- Policies for carousel_slides
create policy "Allow public read access" on public.carousel_slides
  for select using (true);

create policy "Allow authenticated full access" on public.carousel_slides
  for all using (auth.role() = 'authenticated');
